version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.5
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init
  build:
    commands:
      - echo Running Terraform Plan...
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo Applying Terraform Plan...
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
